class Component {
  final String code;
  final String name;
  final String description;
  final String price;
  bool isSelected;
  String? imagePath;

  Component(this.code, this.name, this.description, this.price, this.isSelected,
      {this.imagePath = 'caravan.png'});

  static List<Component> wildDropStandard = [
    Component(
      'DRP-OR-01',
      'Body',
      'Dimensions: 210X550X210 interior height : 140 cm',
      '0',
      false,
    ),
    Component(
      'DRP-OR-02',
      'Lighting',
      'Interior Lighting',
      '0',
      false,
    ),
    Component(
      'DRP-OR-03',
      'Luggage',
      '100 LT Special Luggage Section in the Cabin',
      '0',
      false,
    ),
    Component(
      'DRP-OR-04',
      'Window',
      'Openable Sliding Windows - Mosquito Net and Roller Blind System',
      '0',
      false,
    ),
    Component(
      'DRP-OR-05',
      'Fender',
      'Right-Left Wheel Top Fiber Fender',
      '0',
      false,
    ),
    Component(
      'DRP-OR-06',
      'Exterior Lighting',
      'Jokon Taillight And Reflectors',
      '0',
      false,
    ),
    Component(
      'DRP-OR-07',
      'Floor',
      'Soft Textured Interior Upholstery',
      '0',
      false,
    ),
    Component(
      'DRP-OR-08',
      'Electric System',
      '60A AGM GEL Battery, Battery Charger and Fuse Board',
      '0',
      false,
    ),
    Component(
      'DRP-OR-09',
      'Internal Electricity',
      '220 V Socket - 5 V USB Socket Port',
      '0',
      false,
    ),
    Component(
      'DRP-OR-10',
      'Rim - Tire',
      'Alloy Wheels 15' ' - All-Terrain Tires 195/70/R15',
      '0',
      false,
    ),
    Component(
      'DRP-OR-11',
      'Door - Frame',
      'Right-Left bidirectional entry',
      '0',
      false,
    ),
    Component(
      'DRP-OR-12',
      'Shovel',
      'Multifunctional Off Road Shovel',
      '0',
      false,
    ),
    Component(
      'DRP-OR-13',
      'Control Panel',
      '7' ' HMI Touch Control Panel',
      '0',
      false,
    ),
    Component(
      'DRP-OR-14',
      'Chassis',
      'AL-KO Imported Brake Axle 1000 kg',
      '0',
      false,
    ),
    Component(
      'DRP-OR-15',
      'Tube Holder',
      '250 LT Front External Storage Area',
      '0',
      false,
    ),
    Component(
      'DRP-OR-16',
      'Bed',
      '4 Piece Bed',
      '0',
      false,
    ),
  ];
  static final List<Component> wildDropExtra = [
    Component(
      'DRP-ORO-01',
      'Battery',
      '105 Amp AGM Gel Battery+D24:E39D24:ED24:E40',
      '150',
      false,
      imagePath: 'battery.png',
    ),
    Component(
      'DRP-ORO-02',
      'Alko Impact',
      'ALKO Shock Absorber (2 Pieces)',
      '400',
      false,
      imagePath: 'alko impact.png',
    ),
    Component(
      'DRP-ORO-03',
      'Alko Stabilizer',
      'Alko Stabilizer',
      '700',
      false,
      imagePath: 'alko stabilizer.png',
    ),
    Component(
      'DRP-ORO-04',
      'Stairs',
      'THULE Stairs ( 2PCS )',
      '550',
      false,
      imagePath: 'stairs.png',
    ),
    Component(
      'DRP-ORO-05',
      'Refrigerator',
      'DOMETIC REFRIGERATOR (14L)',
      '299',
      false,
      imagePath: 'dometic refrigerator.png',
    ),
    Component(
      'DRP-ORO-06',
      'Refrigerator',
      'ICE PEAK  REFRIGERATOR',
      '199',
      false,
      imagePath: 'ice peak.png',
    ),
    Component(
      'DRP-ORO-08',
      'Exterior Lighting',
      'JOKON ENVIRONMENT AND EXTERIOR LIGHTING',
      '150',
      false,
      imagePath: 'exterior lighting.png',
    ),
    Component(
      'DRP-ORO-09',
      'Outer Cover',
      'DROPCAMP Offroad Outer Cover',
      '275',
      false,
      imagePath: 'outer cover.png',
    ),
    Component(
      'DRP-ORO-10',
      'Shower',
      'Outdoor Shower System',
      '200',
      false,
      imagePath: 'shower system.png',
    ),
    Component(
      'DRP-ORO-11',
      'Shower',
      'Outdoor Shower Tent',
      '75',
      false,
      imagePath: 'shower tent.png',
    ),
    Component(
      'DRP-ORO-12',
      'Solar Panel',
      'Portable Flexible Solar Panel 12 V 200 Watt SET',
      '2000',
      false,
      imagePath: 'solar panel.jpeg',
    ),
    Component(
      'DRP-ORO-13',
      'Ventilation',
      'DOMETIC VENTILATION',
      '375',
      false,
      imagePath: 'ventilation.png',
    ),
    Component(
      'DRP-ORO-14',
      'Ventilation',
      'TYT BRAND SQUARE BRAND VENTILATION',
      '150',
      false,
      imagePath: 'square ventilation.jpg',
    ),
    Component(
      'DRP-ORO-15',
      'Combi',
      'TRUMA 4E COMBI',
      '2750',
      false,
      imagePath: 'combi.png',
    ),
    Component(
      'DRP-ORO-30',
      'Webasto',
      'Diesel Heating System (webasto)',
      '1350',
      false,
      imagePath: 'webasto.png',
    ),
    Component(
      'DRP-ORO-16',
      'Kitchen',
      'DOMETIC COOK SINK AND FOLDING FAUCET',
      '850',
      false,
      imagePath: 'dometic kitchen.png',
    ),
    Component(
      'DRP-ORO-18',
      'Cook/Sink',
      'CAN Double Burner Cooker and Gas Installation',
      '625',
      false,
      imagePath: 'cook sink.png',
    ),
    Component(
      'DRP-ORO-17',
      'Kitchen',
      'SLIDING KITCHEN MODULE + CONNECTIONS',
      '199',
      false,
      imagePath: 'sliding kitchen.png',
    ),
    Component(
      'DRP-ORO-19',
      'Off-Road Bars',
      'Off-road Aggressive Protection Bars',
      '200',
      false,
      imagePath: 'offroad bar.png',
    ),
    Component(
      'DRP-ORO-21',
      'Swatter',
      'Large Cabin Swatter (2 Pieces)',
      '199',
      false,
      imagePath: 'swatter.png',
    ),
    Component(
      'DRP-ORO-22',
      'Stepne',
      'Spare tire and Steel Rim',
      '500',
      false,
      imagePath: 'stepne.png',
    ),
    Component(
      'DRP-ORO-23',
      'Stepne Sheath',
      'Spare Tire Case',
      '50',
      false,
    ),
    Component(
      'DRP-ORO-24',
      'Stepne Carrying',
      'Spare Tire Metal Housing Front Forehead Offroad Type Connection',
      '150',
      false,
    ),
    Component(
      'DRP-ORO-25',
      'Water Heating System',
      'Truma Term TT WATER HEATING SYSTEM',
      '399',
      false,
      imagePath: 'water heating system.png',
    ),
    Component(
      'DRP-ORO-26',
      'Water System',
      'FULL SET + ASSEMBLY WITH 60 LT TANK',
      '399',
      false,
      imagePath: 'water system.png',
    ),
    Component(
      'DRP-ORO-27',
      'Tent',
      'THULE Tent',
      '1199',
      false,
      imagePath: 'swatter.png',
    ),
    Component(
      'DRP-ORO-28',
      'Gas Cylinder',
      'Gas Cylinder FOR SPECIAL GAS ENTRY KITCHEN AND HEATER',
      '200',
      false,
      imagePath: 'gas cylinder.png',
    ),
    Component(
      'DRP-ORO-29',
      'WC',
      'CASSETTE WC (PORTA POTTİ)',
      '125',
      false,
      imagePath: 'wc.png',
    ),
  ];

  static final List<Component> widenDropStandard = [
    Component(
      'DRP-M-1201',
      'Body',
      'Dimensions: 210X550X210 interior height : 140 cm',
      '0',
      false,
    ),
    Component(
      'DRP-M-1502',
      'Lighting',
      'Interior Lighting',
      '0',
      false,
    ),
    Component(
      'DRP-M-1203',
      'Luggage',
      '100 LT Special Luggage Section in the Cabin',
      '0',
      false,
    ),
    Component(
      'DRP-M-1204',
      'Window',
      'Openable Sliding Windows - Mosquito Net and Roller Blind System',
      '0',
      false,
    ),
    Component(
      'DRP-M-1205',
      'Fender',
      'Right-Left Wheel Top Fiber Fender',
      '0',
      false,
    ),
    Component(
      'DRP-M-1506',
      'Exterior Lighting',
      'Jokon Taillight And Reflectors',
      '0',
      false,
    ),
    Component(
      'DRP-M-1207',
      'Floor',
      'Soft Textured Interior Upholstery',
      '0',
      false,
    ),
    Component(
      'DRP-M-1508',
      'Electric System',
      '60A AGM GEL Battery, Battery Charger and Fuse Board',
      '0',
      false,
    ),
    Component(
      'DRP-M-1509',
      'Internal Electricity',
      '220 V Socket - 5 V USB Socket Port',
      '0',
      false,
    ),
    Component(
      'DRP-M-1210',
      'Rim - Tire',
      'Alloy Wheels 15' ' - All-Terrain Tires 195/70/R15',
      '0',
      false,
    ),
    Component(
      'DRP-M-1211',
      'Door - Frame',
      'Right-Left bidirectional entry',
      '0',
      false,
    ),
    Component(
      'DRP-M-1212',
      'Module',
      'Rear Opening Section as a Set',
      '0',
      false,
    ),
    Component(
      'DRP-M-1513',
      'Control Panel',
      '7' ' HMI Touch Control Panel',
      '0',
      false,
    ),
    Component(
      'DRP-M-1214',
      'Chassis',
      'AL-KO Imported Brake Axle 1000 kg',
      '0',
      false,
    ),
    Component(
      'DRP-M-1215',
      'Tube Holder',
      '250 LT Front External Storage Area',
      '0',
      false,
    ),
    Component(
      'DRP-M-1216',
      'Bed',
      '4 Piece Bed',
      '0',
      false,
    ),
  ];
  static final List<Component> widenDropExtra = [
    Component(
      'DRP-MO-1201',
      wildDropExtra[0].name,
      wildDropExtra[0].description,
      wildDropExtra[0].price,
      false,
      imagePath: 'battery.png',
    ),
    Component(
      'DRP-MO-1202',
      wildDropExtra[1].name,
      wildDropExtra[1].description,
      wildDropExtra[1].price,
      false,
      imagePath: 'alko impact.png',
    ),
    Component(
      'DRP-MO-1203',
      wildDropExtra[2].name,
      wildDropExtra[2].description,
      wildDropExtra[2].price,
      false,
      imagePath: 'alko stabilizer.png',
    ),
    Component(
      'DRP-MO-1204',
      wildDropExtra[3].name,
      wildDropExtra[3].description,
      wildDropExtra[3].price,
      false,
      imagePath: 'stairs.png',
    ),
    Component(
      'DRP-MO-1305',
      wildDropExtra[4].name,
      wildDropExtra[4].description,
      wildDropExtra[4].price,
      false,
      imagePath: 'dometic refrigerator.png',
    ),
    Component(
      'DRP-MO-1306',
      wildDropExtra[5].name,
      wildDropExtra[5].description,
      wildDropExtra[5].price,
      false,
      imagePath: 'ice peak.png',
    ),
    Component(
      'DRP-MO-1508',
      wildDropExtra[6].name,
      wildDropExtra[6].description,
      wildDropExtra[6].price,
      false,
      imagePath: 'exterior lighting.png',
    ),
    Component(
      'DRP-MO-1209',
      wildDropExtra[7].name,
      wildDropExtra[7].description,
      wildDropExtra[7].price,
      false,
      imagePath: 'outer cover.png',
    ),
    Component(
      'DRP-MO-1210',
      wildDropExtra[8].name,
      wildDropExtra[8].description,
      wildDropExtra[8].price,
      false,
      imagePath: 'shower system.png',
    ),
    Component(
      'DRP-MO-1211',
      wildDropExtra[9].name,
      wildDropExtra[9].description,
      wildDropExtra[9].price,
      false,
      imagePath: 'shower tent.png',
    ),
    Component(
      'DRP-MO-1512',
      wildDropExtra[10].name,
      wildDropExtra[10].description,
      wildDropExtra[10].price,
      false,
      imagePath: 'solar panel.jpeg',
    ),
    Component(
      'DRP-MO-1513',
      wildDropExtra[11].name,
      wildDropExtra[11].description,
      wildDropExtra[11].price,
      false,
      imagePath: 'ventilation.png',
    ),
    Component(
      'DRP-MO-1514',
      wildDropExtra[12].name,
      wildDropExtra[12].description,
      wildDropExtra[12].price,
      false,
      imagePath: 'square ventilation.jpg',
    ),
    Component(
      'DRP-MO-1515',
      wildDropExtra[13].name,
      wildDropExtra[13].description,
      wildDropExtra[13].price,
      false,
      imagePath: 'combi.png',
    ),
    Component(
      'DRP-MO-1330',
      wildDropExtra[14].name,
      wildDropExtra[14].description,
      wildDropExtra[14].price,
      false,
      imagePath: 'webasto.png',
    ),
    Component(
      'DRP-MO-1316',
      wildDropExtra[15].name,
      wildDropExtra[15].description,
      wildDropExtra[15].price,
      false,
      imagePath: 'dometic kitchen.png',
    ),
    Component(
      'DRP-MO-1318',
      wildDropExtra[16].name,
      wildDropExtra[16].description,
      wildDropExtra[16].price,
      false,
      imagePath: 'cook sink.png',
    ),
    Component(
      'DRP-MO-1217',
      wildDropExtra[17].name,
      wildDropExtra[17].description,
      wildDropExtra[17].price,
      false,
      imagePath: 'sliding kitchen.png',
    ),
    Component(
      'DRP-MO-1221',
      wildDropExtra[19].name,
      wildDropExtra[19].description,
      wildDropExtra[19].price,
      false,
      imagePath: 'swatter.png',
    ),
    Component(
      'DRP-MO-1425',
      wildDropExtra[23].name,
      wildDropExtra[23].description,
      wildDropExtra[23].price,
      false,
      imagePath: 'water heating system.png',
    ),
    Component(
      'DRP-MO-1426',
      wildDropExtra[24].name,
      wildDropExtra[24].description,
      wildDropExtra[24].price,
      false,
      imagePath: 'water system.png',
    ),
    Component(
      'DRP-MO-1327',
      wildDropExtra[25].name,
      wildDropExtra[25].description,
      wildDropExtra[25].price,
      false,
      imagePath: 'swatter.png',
    ),
    Component(
      'DRP-MO-1328',
      wildDropExtra[26].name,
      wildDropExtra[26].description,
      wildDropExtra[26].price,
      false,
      imagePath: 'gas cylinder.png',
    ),
    Component(
      'DRP-MO-1329',
      wildDropExtra[27].name,
      wildDropExtra[27].description,
      wildDropExtra[27].price,
      false,
      imagePath: 'wc.png',
    ),
  ];
}
