import 'package:pdf_order_creator/localization/locale_keys.g.dart';

class Component {
  final String code;
  final String name;
  final String description;
  final String price;
  bool isSelected;
  String? imagePath;

  Component(this.code, this.name, this.description, this.price, this.isSelected,
      {this.imagePath = 'caravan.png'});

  static List<Component> wildDropStandard = [
    Component(
      'DRP-OR-01',
      LocaleKeys.body,
      LocaleKeys.bodyDescription,
      '0',
      false,
    ),
    Component(
      'DRP-OR-02',
      LocaleKeys.lighting,
      LocaleKeys.lightingDescription,
      '0',
      false,
    ),
    Component(
      'DRP-OR-03',
      LocaleKeys.luggage,
      LocaleKeys.luggageDescription,
      '0',
      false,
    ),
    Component(
      'DRP-OR-04',
      LocaleKeys.window,
      LocaleKeys.windowDescription,
      '0',
      false,
    ),
    Component(
      'DRP-OR-05',
      LocaleKeys.fender,
      LocaleKeys.fenderDescription,
      '0',
      false,
    ),
    Component(
      'DRP-OR-06',
      LocaleKeys.exteriorLighting,
      LocaleKeys.exteriorLightingDescription,
      '0',
      false,
    ),
    Component(
      'DRP-OR-07',
      LocaleKeys.floor,
      LocaleKeys.floorDescription,
      '0',
      false,
    ),
    Component(
      'DRP-OR-08',
      LocaleKeys.electricSystem,
      LocaleKeys.electricSystemDescription,
      '0',
      false,
    ),
    Component(
      'DRP-OR-09',
      LocaleKeys.internalElectricity,
      LocaleKeys.internalElectricityDescription,
      '0',
      false,
    ),
    Component(
      'DRP-OR-10',
      LocaleKeys.rimTire,
      LocaleKeys.rimTireDescription,
      '0',
      false,
    ),
    Component(
      'DRP-OR-11',
      LocaleKeys.doorFrame,
      LocaleKeys.doorFrameDescription,
      '0',
      false,
    ),
    Component(
      'DRP-OR-12',
      LocaleKeys.shovel,
      LocaleKeys.shovelDescription,
      '0',
      false,
    ),
    Component(
      'DRP-OR-13',
      LocaleKeys.controlPanel,
      LocaleKeys.controlPanelDescription,
      '0',
      false,
    ),
    Component(
      'DRP-OR-14',
      LocaleKeys.chassis,
      LocaleKeys.chassisDescription,
      '0',
      false,
    ),
    Component(
      'DRP-OR-15',
      LocaleKeys.tubeHolder,
      LocaleKeys.tubeHolderDescription,
      '0',
      false,
    ),
    Component(
      'DRP-OR-16',
      LocaleKeys.bed,
      LocaleKeys.bedDescription,
      '0',
      false,
    ),
  ];
  static final List<Component> wildDropExtra = [
    Component(
      'DRP-ORO-01',
      LocaleKeys.battery,
      LocaleKeys.batteryDescription,
      '150',
      false,
      imagePath: 'battery.png',
    ),
    Component(
      'DRP-ORO-02',
      LocaleKeys.alkoImpact,
      LocaleKeys.alkoImpactDescription,
      '400',
      false,
      imagePath: 'alko impact.png',
    ),
    Component(
      'DRP-ORO-03',
      LocaleKeys.alkoStabilizer,
      LocaleKeys.alkoStabilizerDescription,
      '700',
      false,
      imagePath: 'alko stabilizer.png',
    ),
    Component(
      'DRP-ORO-04',
      LocaleKeys.stairs,
      LocaleKeys.stairsDescription,
      '550',
      false,
      imagePath: 'stairs.png',
    ),
    Component(
      'DRP-ORO-05',
      LocaleKeys.refrigerator,
      LocaleKeys.refrigeratorDometicDescription,
      '299',
      false,
      imagePath: 'dometic refrigerator.png',
    ),
    Component(
      'DRP-ORO-06',
      LocaleKeys.refrigerator,
      LocaleKeys.refrigeratorDescription,
      '199',
      false,
      imagePath: 'ice peak.png',
    ),
    Component(
      'DRP-ORO-08',
      LocaleKeys.exteriorLightingExtra,
      LocaleKeys.exteriorLightingExtraDescription,
      '150',
      false,
      imagePath: 'exterior lighting.png',
    ),
    Component(
      'DRP-ORO-09',
      LocaleKeys.outerCover,
      LocaleKeys.outerCoverDescription,
      '275',
      false,
      imagePath: 'outer cover.png',
    ),
    Component(
      'DRP-ORO-10',
      LocaleKeys.shower,
      LocaleKeys.showerSystemDescription,
      '200',
      false,
      imagePath: 'shower system.png',
    ),
    Component(
      'DRP-ORO-11',
      LocaleKeys.shower,
      LocaleKeys.showerDescription,
      '75',
      false,
      imagePath: 'shower tent.png',
    ),
    Component(
      'DRP-ORO-12',
      LocaleKeys.solarPanel,
      LocaleKeys.solarPanelDescription,
      '2000',
      false,
      imagePath: 'solar panel.jpeg',
    ),
    Component(
      'DRP-ORO-13',
      LocaleKeys.ventilation,
      LocaleKeys.ventilationDometicDescription,
      '375',
      false,
    ),
    Component(
      'DRP-ORO-14',
      LocaleKeys.ventilation,
      LocaleKeys.ventilationDescription,
      '150',
      false,
      imagePath: 'square ventilation.jpg',
    ),
    Component(
      'DRP-ORO-15',
      LocaleKeys.combi,
      LocaleKeys.combiDescription,
      '2750',
      false,
      imagePath: 'combi.png',
    ),
    Component(
      'DRP-ORO-30',
      LocaleKeys.webasto,
      LocaleKeys.webastoDescription,
      '1350',
      false,
      imagePath: 'webasto.png',
    ),
    Component(
      'DRP-ORO-16',
      LocaleKeys.kitchen,
      LocaleKeys.kitchenDometicDescription,
      '850',
      false,
      imagePath: 'dometic kitchen.png',
    ),
    Component(
      'DRP-ORO-18',
      LocaleKeys.cookSink,
      LocaleKeys.cookSinkDescription,
      '625',
      false,
      imagePath: 'cook sink.png',
    ),
    Component(
      'DRP-ORO-17',
      LocaleKeys.kitchen,
      LocaleKeys.kitchenDescription,
      '199',
      false,
      imagePath: 'sliding kitchen.png',
    ),
    Component(
      'DRP-ORO-19',
      LocaleKeys.offRoadBars,
      LocaleKeys.offRoadBarsDescription,
      '200',
      false,
      imagePath: 'offroad bar.png',
    ),
    Component(
      'DRP-ORO-21',
      LocaleKeys.swatter,
      LocaleKeys.swatterDescription,
      '199',
      false,
      imagePath: 'ventilation.png',
    ),
    Component(
      'DRP-ORO-22',
      LocaleKeys.stepne,
      LocaleKeys.stepneDescription,
      '500',
      false,
      imagePath: 'stepne.png',
    ),
    Component(
      'DRP-ORO-23',
      LocaleKeys.stepneSheath,
      LocaleKeys.stepneSheathDescription,
      '50',
      false,
    ),
    Component(
      'DRP-ORO-24',
      LocaleKeys.stepneCarrying,
      LocaleKeys.stepneCarryingDescription,
      '150',
      false,
    ),
    Component(
      'DRP-ORO-25',
      LocaleKeys.waterHeatingSystem,
      LocaleKeys.waterHeatingSystemDescription,
      '399',
      false,
      imagePath: 'water heating system.png',
    ),
    Component(
      'DRP-ORO-26',
      LocaleKeys.waterSystem,
      LocaleKeys.waterSystemDescription,
      '399',
      false,
      imagePath: 'water system.png',
    ),
    Component(
      'DRP-ORO-27',
      LocaleKeys.tent,
      LocaleKeys.tentDescription,
      '1199',
      false,
      imagePath: 'swatter.png',
    ),
    Component(
      'DRP-ORO-28',
      LocaleKeys.gasCylinder,
      LocaleKeys.gasCylinderDescription,
      '200',
      false,
      imagePath: 'gas cylinder.png',
    ),
    Component(
      'DRP-ORO-29',
      LocaleKeys.wc,
      LocaleKeys.wcDescription,
      '125',
      false,
      imagePath: 'wc.png',
    ),
  ];

  static final List<Component> widenDropStandard = [
    Component(
      'DRP-M-1201',
      wildDropStandard[0].name,
      wildDropStandard[0].description,
      '0',
      false,
    ),
    Component(
      'DRP-M-1502',
      wildDropStandard[1].name,
      wildDropStandard[1].description,
      '0',
      false,
    ),
    Component(
      'DRP-M-1203',
      wildDropStandard[2].name,
      wildDropStandard[2].description,
      '0',
      false,
    ),
    Component(
      'DRP-M-1204',
      wildDropStandard[3].name,
      wildDropStandard[3].description,
      '0',
      false,
    ),
    Component(
      'DRP-M-1205',
      wildDropStandard[4].name,
      wildDropStandard[4].description,
      '0',
      false,
    ),
    Component(
      'DRP-M-1506',
      wildDropStandard[5].name,
      wildDropStandard[5].description,
      '0',
      false,
    ),
    Component(
      'DRP-M-1207',
      wildDropStandard[6].name,
      wildDropStandard[6].description,
      '0',
      false,
    ),
    Component(
      'DRP-M-1508',
      wildDropStandard[7].name,
      wildDropStandard[7].description,
      '0',
      false,
    ),
    Component(
      'DRP-M-1509',
      wildDropStandard[8].name,
      wildDropStandard[8].description,
      '0',
      false,
    ),
    Component(
      'DRP-M-1210',
      wildDropStandard[9].name,
      wildDropStandard[9].description,
      '0',
      false,
    ),
    Component(
      'DRP-M-1211',
      wildDropStandard[10].name,
      wildDropStandard[10].description,
      '0',
      false,
    ),
    Component(
      'DRP-M-1212',
      LocaleKeys.module,
      LocaleKeys.moduleDescription,
      '0',
      false,
    ),
    Component(
      'DRP-M-1513',
      wildDropStandard[12].name,
      wildDropStandard[12].description,
      '0',
      false,
    ),
    Component(
      'DRP-M-1214',
      wildDropStandard[13].name,
      wildDropStandard[13].description,
      '0',
      false,
    ),
    Component(
      'DRP-M-1215',
      wildDropStandard[14].name,
      wildDropStandard[14].description,
      '0',
      false,
    ),
    Component(
      'DRP-M-1216',
      wildDropStandard[15].name,
      wildDropStandard[15].description,
      '0',
      false,
    ),
  ];
  static final List<Component> widenDropExtra = [
    Component(
      'DRP-MO-1201',
      wildDropExtra[0].name,
      wildDropExtra[0].description,
      wildDropExtra[0].price,
      false,
      imagePath: 'battery.png',
    ),
    Component(
      'DRP-MO-1202',
      wildDropExtra[1].name,
      wildDropExtra[1].description,
      wildDropExtra[1].price,
      false,
      imagePath: 'alko impact.png',
    ),
    Component(
      'DRP-MO-1203',
      wildDropExtra[2].name,
      wildDropExtra[2].description,
      wildDropExtra[2].price,
      false,
      imagePath: 'alko stabilizer.png',
    ),
    Component(
      'DRP-MO-1204',
      wildDropExtra[3].name,
      wildDropExtra[3].description,
      wildDropExtra[3].price,
      false,
      imagePath: 'stairs.png',
    ),
    Component(
      'DRP-MO-1305',
      wildDropExtra[4].name,
      wildDropExtra[4].description,
      wildDropExtra[4].price,
      false,
      imagePath: 'dometic refrigerator.png',
    ),
    Component(
      'DRP-MO-1306',
      wildDropExtra[5].name,
      wildDropExtra[5].description,
      wildDropExtra[5].price,
      false,
      imagePath: 'ice peak.png',
    ),
    Component(
      'DRP-MO-1508',
      wildDropExtra[6].name,
      wildDropExtra[6].description,
      wildDropExtra[6].price,
      false,
      imagePath: 'exterior lighting.png',
    ),
    Component(
      'DRP-MO-1209',
      wildDropExtra[7].name,
      wildDropExtra[7].description,
      wildDropExtra[7].price,
      false,
      imagePath: 'outer cover.png',
    ),
    Component(
      'DRP-MO-1210',
      wildDropExtra[8].name,
      wildDropExtra[8].description,
      wildDropExtra[8].price,
      false,
      imagePath: 'shower system.png',
    ),
    Component(
      'DRP-MO-1211',
      wildDropExtra[9].name,
      wildDropExtra[9].description,
      wildDropExtra[9].price,
      false,
      imagePath: 'shower tent.png',
    ),
    Component(
      'DRP-MO-1512',
      wildDropExtra[10].name,
      wildDropExtra[10].description,
      wildDropExtra[10].price,
      false,
      imagePath: 'solar panel.jpeg',
    ),
    Component(
      'DRP-MO-1513',
      wildDropExtra[11].name,
      wildDropExtra[11].description,
      wildDropExtra[11].price,
      false,
    ),
    Component(
      'DRP-MO-1514',
      wildDropExtra[12].name,
      wildDropExtra[12].description,
      wildDropExtra[12].price,
      false,
      imagePath: 'square ventilation.jpg',
    ),
    Component(
      'DRP-MO-1515',
      wildDropExtra[13].name,
      wildDropExtra[13].description,
      wildDropExtra[13].price,
      false,
      imagePath: 'combi.png',
    ),
    Component(
      'DRP-MO-1330',
      wildDropExtra[14].name,
      wildDropExtra[14].description,
      wildDropExtra[14].price,
      false,
      imagePath: 'webasto.png',
    ),
    Component(
      'DRP-MO-1316',
      wildDropExtra[15].name,
      wildDropExtra[15].description,
      wildDropExtra[15].price,
      false,
      imagePath: 'dometic kitchen.png',
    ),
    Component(
      'DRP-MO-1318',
      wildDropExtra[16].name,
      wildDropExtra[16].description,
      wildDropExtra[16].price,
      false,
      imagePath: 'cook sink.png',
    ),
    Component(
      'DRP-MO-1217',
      wildDropExtra[17].name,
      wildDropExtra[17].description,
      wildDropExtra[17].price,
      false,
      imagePath: 'sliding kitchen.png',
    ),
    Component(
      'DRP-MO-1221',
      wildDropExtra[19].name,
      wildDropExtra[19].description,
      wildDropExtra[19].price,
      false,
      imagePath: 'ventilation.png',
    ),
    Component(
      'DRP-MO-1425',
      wildDropExtra[23].name,
      wildDropExtra[23].description,
      wildDropExtra[23].price,
      false,
      imagePath: 'water heating system.png',
    ),
    Component(
      'DRP-MO-1426',
      wildDropExtra[24].name,
      wildDropExtra[24].description,
      wildDropExtra[24].price,
      false,
      imagePath: 'water system.png',
    ),
    Component(
      'DRP-MO-1327',
      wildDropExtra[25].name,
      wildDropExtra[25].description,
      wildDropExtra[25].price,
      false,
      imagePath: 'swatter.png',
    ),
    Component(
      'DRP-MO-1328',
      wildDropExtra[26].name,
      wildDropExtra[26].description,
      wildDropExtra[26].price,
      false,
      imagePath: 'gas cylinder.png',
    ),
    Component(
      'DRP-MO-1329',
      wildDropExtra[27].name,
      wildDropExtra[27].description,
      wildDropExtra[27].price,
      false,
      imagePath: 'wc.png',
    ),
  ];
}
